DELETE FROM MVCore_Wshopp_Ertel
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (1,1,'Elemental Dmg',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,1,'Attack Against Fire Element',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,2,'Attack Against Water Element',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,3,'Attack Against Earth Element',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,4,'Attack Against Wind Element',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,5,'Attack Against Dark Element',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,1,'Elemental Attack Dmg (in PvP)',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,2,'Elemental Attack Dmg (in Raids)',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,1,'Ranged Elemental Attack Dmg (in PvP)',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,2,'Melee Elemental Attack Dmg (in PvP)',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,1,'Elemental Critical Rate (in PvP)',221)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,2,'Elemental Critical Rate (in Raids)',221)

INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (1,1,'Elemental Defense',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,1,'Defense Against Fire Element',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,2,'Defense Against Water Element',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,3,'Defense Against Earth Element',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,4,'Defense Against Wind Element',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,5,'Defense Against Dark Element',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,1,'Elemental Defense (in PvP)',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,2,'Elemental Defense (in Raids)',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,1,'Ranged Elemental Defense (in PvP)',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,2,'Melee Elemental Defense (in PvP)',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,1,'Elemental Dmg (in PvP)',231)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,2,'Elemental Dmg (in Raids)',231)

INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (1,1,'Elemental Attack Success Rate',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,1,'Attack Against Fire Element',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,2,'Attack Against Water Element',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,3,'Attack Against Earth Element',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,4,'Attack Against Wind Element',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,5,'Attack Against Dark Element',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,1,'Elemental Attack Dmg (in PvP)',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,2,'Elemental Attack Dmg (in Raids)',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,1,'Ranged Elemental Attack Dmg (in PvP)',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,2,'Melee Elemental Attack Dmg (in PvP)',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,1,'Elemental Damage (in PvP)',241)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,2,'Elemental Damage (in Raids)',241)

INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (1,1,'Elemental Defense Success Rate',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,1,'Defense Against Fire Element',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,2,'Defense Against Water Element',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,3,'Defense Against Earth Element',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,4,'Defense Against Wind Element',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,5,'Defense Against Dark Element',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,1,'Elemental Defense (in PvP)',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,2,'Elemental Defense (in Raids)',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,1,'Ranged Elemental Defense (in PvP)',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,2,'Melee Elemental Defense (in PvP)',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,1,'Elemental Damage Absorb (in PvP)',251)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,2,'Elemental Damage Absorb (in Raids)',251)

INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (1,1,'Elemental Debuff Success Rate',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,1,'Strength increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,2,'Agility increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,3,'Energy increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (2,4,'Stamina increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,1,'Maximum HP increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,2,'Maximum Mana increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,3,'Maximum AG increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (3,4,'Maximum SP increase',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,1,'Elemental Attack Excellent Rate (in PvP)',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (4,2,'Elemental Attack Excellent Rate (in Raids)',261)
INSERT INTO MVCore_Wshopp_Ertel (ertel_cat,ertel_id,ertel_name,ertel_type)VALUES (5,1,'Additional Elemental Occurence Chance',261)