DELETE FROM MVCore_Wshopp_Harmony
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,6,'Attack (Max Min) +7',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,7,'Attack (Max Min) +8',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,8,'Attack (Max Min) +9',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,9,'Attack (Max Min) +11',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,10,'Attack (Max Min) +12',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,11,'Attack (Max Min) +14',1,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,12,'Attack (Max Min) +16',1,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,13,'Attack (Max Min) +19',1,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,0,'Min attack increase +2',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,1,'Min attack increase +3',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,2,'Min attack increase +4',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,3,'Min attack increase +5',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,4,'Min attack increase +6',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,5,'Min attack increase +7',1,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,6,'Min attack increase +9',1,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,7,'Min attack increase +11',1,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,8,'Min attack increase +12',1,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,9,'Min attack increase +14',1,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,10,'Min attack increase +15',1,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,11,'Min attack increase +16',1,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,12,'Min attack increase +17',1,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,13,'Min attack increase +20',1,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,0,'Max attack increase +3',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,1,'Max attack increase +4',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,2,'Max attack increase +5',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,3,'Max attack increase +6',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,4,'Max attack increase +7',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,5,'Max attack increase +8',1,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,6,'Max attack increase +10',1,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,7,'Max attack increase +12',1,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,8,'Max attack increase +14',1,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,9,'Max attack increase +17',1,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,10,'Max attack increase +20',1,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,11,'Max attack increase +23',1,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,12,'Max attack increase +26',1,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,13,'Max attack increase +29',1,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,0,'Required strength decrease +6',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,1,'Required strength decrease +8',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,2,'Required strength decrease +10',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,3,'Required strength decrease +12',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,4,'Required strength decrease +14',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,5,'Required strength decrease +16',1,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,6,'Required strength decrease +20',1,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,7,'Required strength decrease +23',1,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,8,'Required strength decrease +26',1,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,9,'Required strength decrease +29',1,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,10,'Required strength decrease +32',1,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,11,'Required strength decrease +35',1,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,12,'Required strength decrease +37',1,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,13,'Required strength decrease +40',1,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,0,'Required agility decrease +6',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,1,'Required agility decrease +8',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,2,'Required agility decrease +10',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,3,'Required agility decrease +12',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,4,'Required agility decrease +14',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,5,'Required agility decrease +16',1,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,6,'Required agility decrease +20',1,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,7,'Required agility decrease +23',1,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,8,'Required agility decrease +26',1,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,9,'Required agility decrease +29',1,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,10,'Required agility decrease +32',1,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,11,'Required agility decrease +35',1,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,12,'Required agility decrease +37',1,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,13,'Required agility decrease +40',1,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,6,'Critical Damage increase +6',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,7,'Critical Damage increase +14',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,8,'Critical Damage increase +16',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,9,'Critical Damage increase +18',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,10,'Critical Damage increase +20',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,11,'Critical Damage increase +22',1,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,12,'Critical Damage increase +24',1,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,13,'Critical Damage increase +30',1,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,9,'Skill Damage increase +12',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,10,'Skill Damage increase +14',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,11,'Skill Damage increase +16',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,12,'Skill Damage increase +18',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,13,'Skill Damage increase +22',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (8,9,'Attack Success Rate (PvP) increase 5%',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (8,10,'Attack Success Rate (PvP) increase 7%',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (8,11,'Attack Success Rate (PvP) increase 9%',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (8,12,'Attack Success Rate (PvP) increase 11%',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (8,13,'Attack Success Rate (PvP) increase 14%',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (9,9,'SD Reduction 3%',1,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (9,10,'SD Reduction 5%',1,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (9,11,'SD Reduction 7%',1,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (9,12,'SD Reduction 9%',1,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (9,13,'SD Reduction 10%',1,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (10,13,'SD Ignore Rate 10%',1,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,0,'Wizardly attack increase +6',2,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,1,'Wizardly attack increase +8',2,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,2,'Wizardly attack increase +10',2,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,3,'Wizardly attack increase +12',2,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,4,'Wizardly attack increase +14',2,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,5,'Wizardly attack increase +16',2,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,6,'Wizardly attack increase +17',2,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,7,'Wizardly attack increase +18',2,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,8,'Wizardly attack increase +19',2,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,9,'Wizardly attack increase +21',2,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,10,'Wizardly attack increase +23',2,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,11,'Wizardly attack increase +25',2,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,12,'Wizardly attack increase +27',2,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,13,'Wizardly attack increase +31',2,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,0,'Required strength decrease +6',2,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,1,'Required strength decrease +8',2,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,2,'Required strength decrease +10',2,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,3,'Required strength decrease +12',2,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,4,'Required strength decrease +14',2,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,5,'Required strength decrease +16',2,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,6,'Required strength decrease +20',2,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,7,'Required strength decrease +23',2,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,8,'Required strength decrease +26',2,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,9,'Required strength decrease +29',2,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,10,'Required strength decrease +32',2,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,11,'Required strength decrease +35',2,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,12,'Required strength decrease +37',2,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,13,'Required strength decrease +40',2,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,0,'Required agility decrease +6',2,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,1,'Required agility decrease +8',2,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,2,'Required agility decrease +10',2,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,3,'Required agility decrease +12',2,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,4,'Required agility decrease +14',2,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,5,'Required agility decrease +16',2,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,6,'Required agility decrease +20',2,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,7,'Required agility decrease +23',2,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,8,'Required agility decrease +26',2,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,9,'Required agility decrease +29',2,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,10,'Required agility decrease +32',2,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,11,'Required agility decrease +35',2,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,12,'Required agility decrease +37',2,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,13,'Required agility decrease +40',2,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,6,'Skill Damage increase +7',2,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,7,'Skill Damage increase +10',2,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,8,'Skill Damage increase +13',2,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,9,'Skill Damage increase +16',2,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,10,'Skill Damage increase +19',2,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,11,'Skill Damage increase +22',2,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,12,'Skill Damage increase +25',2,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,13,'Skill Damage increase +30',2,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,6,'Critical Damage increase +10',2,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,7,'Critical Damage increase +12',2,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,8,'Critical Damage increase +14',2,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,9,'Critical Damage increase +16',2,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,10,'Critical Damage increase +18',2,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,11,'Critical Damage increase +20',2,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,12,'Critical Damage increase +22',2,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,13,'Critical Damage increase +28',2,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,9,'SD Reduction +4%',2,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,10,'SD Reduction +6%',2,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,11,'SD Reduction +8%',2,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,12,'SD Reduction +10%',2,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,13,'SD Reduction +13%',2,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,9,'Attack Success Rate (PvP) increase +5%',2,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,10,'Attack Success Rate (PvP) increase +7%',2,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,11,'Attack Success Rate (PvP) increase +9%',2,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,12,'Attack Success Rate (PvP) increase +11%',2,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,13,'Attack Success Rate (PvP) increase +14%',2,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (8,13,'SD Ignore Rate +15%',2,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,0,'Defense increase +3',3,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,1,'Defense increase +4',3,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,2,'Defense increase +5',3,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,3,'Defense increase +6',3,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,4,'Defense increase +7',3,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,5,'Defense increase +8',3,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,6,'Defense increase +10',3,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,7,'Defense increase +12',3,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,8,'Defense increase +14',3,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,9,'Defense increase +16',3,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,10,'Defense increase +18',3,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,11,'Defense increase +20',3,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,12,'Defense increase +22',3,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (1,13,'Defense increase +25',3,640,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,3,'Max. AG increase +4',3,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,4,'Max. AG increase +6',3,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,5,'Max. AG increase +8',3,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,6,'Max. AG increase +10',3,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,7,'Max. AG increase +12',3,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,8,'Max. AG increase +14',3,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,9,'Max. AG increase +16',3,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,10,'Max. AG increase +18',3,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,11,'Max. AG increase +20',3,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,12,'Max. AG increase +22',3,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (2,13,'Max. AG increase +25',3,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,3,'Max. HP increase +7',3,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,4,'Max. HP increase +9',3,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,5,'Max. HP increase +11',3,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,6,'Max. HP increase +13',3,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,7,'Max. HP increase +15',3,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,8,'Max. HP increase +17',3,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,9,'Max. HP increase +19',3,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,10,'Max. HP increase +21',3,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,11,'Max. HP increase +23',3,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,12,'Max. HP increase +25',3,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (3,13,'Max. HP increase +30',3,400,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,6,'Life auto increment increase +1',3,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,7,'Life auto increment increase +2',3,310,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,8,'Life auto increment increase +3',3,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,9,'Life auto increment increase +4',3,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,10,'Life auto increment increase +5',3,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,11,'Life auto increment increase +6',3,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,12,'Life auto increment increase +7',3,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (4,13,'Life auto increment increase +8',3,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,6,'Mana auto increment increase +1',3,300,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,7,'Mana auto increment increase +2',3,320,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,8,'Mana auto increment increase +3',3,330,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,9,'Mana auto increment increase +4',3,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,10,'Mana auto increment increase +5',3,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,11,'Mana auto increment increase +6',3,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,12,'Mana auto increment increase +7',3,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (5,13,'Mana auto increment increase +8',3,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,9,'Defense success rate increase(PVP) +3',3,340,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,10,'Defense success rate increase(PVP) +4',3,350,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,11,'Defense success rate increase(PVP) +5',3,360,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,12,'Defense success rate increase(PVP) +6',3,370,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (6,13,'Defense success rate increase(PVP) +8',3,380,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,9,'Damage decrement increase +3%',3,390,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,10,'Damage decrement increase +4%',3,600,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,11,'Damage decrement increase +5%',3,610,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,12,'Damage decrement increase +6%',3,620,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (7,13,'Damage decrement increase +7%',3,630,1)
INSERT INTO MVCore_Wshopp_Harmony (joh_id,joh_val,joh_name,joh_type,joh_cost,joh_onoff)VALUES (8,13,'SD Ratio Rate increase +5%',3,600,1)