DELETE FROM MVCore_Wshopp_Socket
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (21,'Wind (Automatic Life Recovery Increase) + 8', 2, 700, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (71,'Wind (Automatic Life Recovery Increase) + 10', 2, 800, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (121,'Wind (Automatic Life Recovery Increase) + 13', 2, 900, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (171,'Wind (Automatic Life Recovery Increase) + 16', 2, 1000, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (221,'Wind (Automatic Life Recovery Increase) + 20', 2, 1100, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (22,'Wind (Maximum Life Increase) + 4%', 2, 600, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (72,'Wind (Maximum Life Increase) + 5%', 2, 700, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (122,'Wind (Maximum Life Increase) + 6%', 2, 800, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (172,'Wind (Maximum Life Increase) + 7%', 2, 900, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (222,'Wind (Maximum Life Increase) + 8%', 2, 1000, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (23,'Wind (Maximum Mana Increase) + 4%', 2, 500, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (73,'Wind (Maximum Mana Increase) + 5%', 2, 600, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (123,'Wind (Maximum Mana Increase) + 6%', 2, 700, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (173,'Wind (Maximum Mana Increase) + 7%', 2, 800, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (223,'Wind (Maximum Mana Increase) + 8%', 2, 900, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (24,'Wind (Automatic Mana Recovery Increase) + 7', 2, 500, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (74,'Wind (Automatic Mana Recovery Increase) + 7', 2, 600, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (124,'Wind (Automatic Mana Recovery Increase) + 21', 2, 700, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (174,'Wind (Automatic Mana Recovery Increase) + 28', 2, 800, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (224,'Wind (Automatic Mana Recovery Increase) + 35', 2, 900, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (25,'Wind (Maximum AG Increase) + 25', 2, 500, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (75,'Wind (Maximum AG Increase) + 30', 2, 600, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (125,'Wind (Maximum AG Increase) + 35', 2, 700, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (175,'Wind (Maximum AG Increase) + 40', 2, 800, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (225,'Wind (Maximum AG Increase) + 50', 2, 900, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (26,'Wind (AG Value Increase) + 3', 2, 500, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (76,'Wind (AG Value Increase) + 5', 2, 600, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (126,'Wind (AG Value Increase) + 7', 2, 700, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (176,'Wind (AG Value Increase) + 10', 2, 800, 6, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (226,'Wind (AG Value Increase) + 15', 2, 900, 6, 1)

INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (29,'Lightning (Excellent Damage Increase) + 15', 1, 600, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (79,'Lightning (Excellent Damage Increase) + 20', 1, 700, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (129,'Lightning (Excellent Damage Increase) + 25', 1, 800, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (179,'Lightning (Excellent Damage Increase) + 30', 1, 900, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (229,'Lightning (Excellent Damage Increase) + 40', 1, 1000, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (30,'Lightning (Excellent Damage Rate Increase) + 10%', 1, 800, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (80,'Lightning (Excellent Damage Rate Increase) + 11%', 1, 900, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (130,'Lightning (Excellent Damage Rate Increase) + 12%', 1, 1000, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (180,'Lightning (Excellent Damage Rate Increase) + 13%', 1, 1100, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (230,'Lightning (Excellent Damage Rate Increase) + 14%', 1, 1200, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (31,'Lightning (Critical Damage Increase) + 30', 1, 600, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (81,'Lightning (Critical Damage Increase) + 32', 1, 700, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (131,'Lightning (Critical Damage Increase) + 35', 1, 800, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (181,'Lightning (Critical Damage Increase) + 40', 1, 900, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (231,'Lightning (Critical Damage Increase) + 50', 1, 1000, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (32,'Lightning (Critical Damage Rate Increase) + 8%', 1, 800, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (82,'Lightning (Critical Damage Rate Increase) + 9%', 1, 900, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (132,'Lightning (Critical Damage Rate Increase) + 10%', 1, 1000, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (182,'Lightning (Critical Damage Rate Increase) + 11%', 1, 1100, 4, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (232,'Lightning (Critical Damage Rate Increase) + 12%', 1, 1200, 4, 1)

INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (36,'Ground (Health Increase) + 30', 2, 500, 2, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (86,'Ground (Health Increase) + 32', 2, 600, 2, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (136,'Ground (Health Increase) + 34', 2, 700, 2, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (186,'Ground (Health Increase) + 36', 2, 800, 2, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (236,'Ground (Health Increase) + 38', 2, 900, 2, 1)

INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (254,'EMPTY (No Mounting Socket)', 0, 0, 1, 1)

INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (0,'Fire (Increase Damage/SkillPower (*lvl)) + 20', 1, 600, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (50,'Fire (Increase Damage/SkillPower (*lvl)) + 19', 1, 700, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (100,'Fire (Increase Damage/SkillPower (*lvl)) + 18', 1, 800, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (150,'Fire (Increase Damage/SkillPower (*lvl)) + 17', 1, 900, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (200,'Fire (Increase Damage/SkillPower (*lvl)) + 14', 1, 1000, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (1,'Fire (Increase Attack Speed) + 7', 1, 600, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (51,'Fire (Increase Attack Speed) + 8', 1, 700, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (101,'Fire (Increase Attack Speed) + 9', 1, 800, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (151,'Fire (Increase Attack Speed) + 10', 1, 900, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (201,'Fire (Increase Attack Speed) + 11', 1, 1000, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (2,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 600, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (52,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 700, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (102,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 800, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (152,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 900, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (202,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 1000, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (3,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 600, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (53,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 700, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (103,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 800, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (153,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 900, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (203,'Fire (Increase Maximum Damage/Skill Power) + 30', 1, 1000, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (4,'Fire (Attack/Wizardry Increase) + 20', 1, 600, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (54,'Fire (Attack/Wizardry Increase) + 22', 1, 700, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (104,'Fire (Attack/Wizardry Increase) + 25', 1, 800, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (150,'Fire (Attack/Wizardry Increase) + 30', 1, 900, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (204,'Fire (Attack/Wizardry Increase) + 35', 1, 1000, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (5,'Fire (AG Cost Decrease) + 40%', 1, 600, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (55,'Fire (AG Cost Decrease) + 41%', 1, 700, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (105,'Fire (AG Cost Decrease) + 42%', 1, 800, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (155,'Fire (AG Cost Decrease) + 43%', 1, 900, 7, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (205,'Fire (AG Cost Decrease) + 44%', 1, 1000, 7, 1)

INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (10,'Water (Block rating increase) + 10%', 2, 900, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (60,'Water (Block rating increase) + 11%', 2, 1000, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (110,'Water (Block rating increase) + 12%', 2, 1100, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (160,'Water (Block rating increase) + 13%', 2, 1200, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (210,'Water (Block rating increase) + 14%', 2, 1300, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (11,'Water (Defense Increase) + 30', 2, 500, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (61,'Water (Defense Increase) + 33', 2, 600, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (111,'Water (Defense Increase) + 36', 2, 700, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (161,'Water (Defense Increase) + 39', 2, 800, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (211,'Water (Defense Increase) + 42', 2, 900, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (12,'Water (Shield Protection Increase) + 7%', 2, 800, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (62,'Water (Shield Protection Increase) + 10%', 2, 900, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (112,'Water (Shield Protection Increase) + 15%', 2, 1000, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (162,'Water (Shield Protection Increase) + 20%', 2, 1100, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (212,'Water (Shield Protection Increase) + 30%', 2, 1200, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (13,'Water (Damage Reduction) + 4%', 2, 900, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (63,'Water (Damage Reduction) + 5%', 2, 1000, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (113,'Water (Damage Reduction) + 6%', 2, 1100, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (163,'Water (Damage Reduction) + 7%', 2, 1200, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (213,'Water (Damage Reduction) + 8%', 2, 1300, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (14,'Water (Damage Reflections) + 5%', 2, 900, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (64,'Water (Damage Reflections) + 6%', 2, 1000, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (114,'Water (Damage Reflections) + 7%', 2, 1100, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (164,'Water (Damage Reflections) + 8%', 2, 1200, 5, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (214,'Water (Damage Reflections) + 9%', 2, 1300, 5, 1)

INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (16,'Ice (Monster desc For The Life Increase) + 8', 1, 400, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (66,'Ice (Monster desc For The Life Increase) + 49', 1, 500, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (116,'Ice (Monster desc For The Life Increase) + 50', 1, 600, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (166,'Ice (Monster desc For The Life Increase) + 51', 1, 700, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (216,'Ice (Monster desc For The Life Increase) + 52', 1, 800, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (17,'Ice (Monster desc For The Life Increase) + 9', 1, 400, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (67,'Ice (Monster desc For The Life Increase) + 49', 1, 500, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (117,'Ice (Monster desc For The Life Increase) + 50', 1, 600, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (167,'Ice (Monster desc For The Life Increase) + 51', 1, 700, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (217,'Ice (Monster desc For The Life Increase) + 52', 1, 800, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (18,'Ice (Skill Attack Increase) + 37', 1, 600, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (68,'Ice (Skill Attack Increase) + 40', 1, 700, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (118,'Ice (Skill Attack Increase) + 45', 1, 800, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (168,'Ice (Skill Attack Increase) + 50', 1, 900, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (218,'Ice (Skill Attack Increase) + 60', 1, 1000, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (19,'Ice (Attack Rating Increase) + 25', 1, 600, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (69,'Ice (Attack Rating Increase) + 27', 1, 700, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (119,'Ice (Attack Rating Increase) + 30', 1, 800, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (169,'Ice (Attack Rating Increase) + 35', 1, 900, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (219,'Ice (Attack Rating Increase) + 40', 1, 1000, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (20,'Ice (Item Duarability Increase) + 30%', 1, 400, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (70,'Ice (Item Duarability Increase) + 32%', 1, 500, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (120,'Ice (Item Duarability Increase) + 34%', 1, 600, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (170,'Ice (Item Duarability Increase) + 36%', 1, 700, 3, 1)
INSERT INTO MVCore_Wshopp_Socket (sok_id,sok_name,type,sok_cost,sok_element,sok_on_off)VALUES (220,'Ice (Item Duarability Increase) + 38%', 1, 800, 3, 1)